### ISSUE TITLE
c# version of MultiProxyPoliteCrawler

### ISSUE THREAD

**Issue by jimjonesGIT** [mnta/Abot.MultiProxyPoliteWebCrawler.FSharp#1]
Do you have a C# version of the MultiProxyPoliteCrawler solution? That would be great!

**Comment by mnta** [comment]
Please see https://github.com/sjdirect/abot/issues/74

**Comment by mnta** [comment]
Please see https://github.com/sjdirect/abot/issues/74

**Comment by mnta** [comment]
See new repository for C# version at https://github.com/mnta/Abot.MultiProxyPoliteWebCrawler

Cheers
